"""Huffman tables of the KamLAND ATWD waveform compression (``DiffDetEntStatHuffComp0.1``).

The tables were generated by Dan Dwyer and Mikhail Batygov (2002) and live in
the collaboration's ``WFComp/trees.hh``; they are part of the private data
format and are therefore *not* shipped with this package.  They are read from
the JSON file named by ``huffman_tables`` in ``claudland.toml`` (see
:mod:`claudland.config`), with keys

``NBITS[s]``, ``CODES[s]``
    Huffman code length and code word of symbol *s* (0..1023, the transformed
    sample differences);
``TABLE[t]``
    12-bit lookup: a value >= 2048 means symbol ``value - 2048`` with length
    ``NBITS[symbol]``; otherwise an index into ``TREE`` for the bit-by-bit
    continuation of codes longer than 12 bits;
``TREE[i]``
    binary tree nodes in pairs (``TREE[ptr + bit]``); a value >= 2048 is a leaf.

The module attributes ``NBITS``, ``CODES``, ``TABLE`` and ``TREE`` are loaded
lazily on first access (PEP 562), so importing :mod:`claudland` works without
the private file; decoding compressed waveforms does not.
"""
from __future__ import annotations

import json
from typing import Dict, List

__all__ = ["NBITS", "CODES", "TABLE", "TREE", "load", "available"]

_NAMES = ("NBITS", "CODES", "TABLE", "TREE")
_tables: Dict[str, List[int]] = {}


def load(path=None) -> Dict[str, List[int]]:
    """Load (and cache) the tables from *path* or from the configured location."""
    global _tables
    if not _tables or path is not None:
        from . import config
        p = config.get().require("huffman_tables") if path is None else path
        with open(p) as fh:
            doc = json.load(fh)
        t = {k: [int(v) for v in doc[k]] for k in _NAMES}
        if len(t["NBITS"]) != 1024 or len(t["TABLE"]) != 4096:
            raise ValueError(f"unexpected Huffman table sizes in {p}")
        _tables = t
    return _tables


def available() -> bool:
    """True if the private table file exists at the configured location."""
    from . import config
    return config.get().huffman_tables.exists()


def __getattr__(name: str):
    if name in _NAMES:
        return tuple(load()[name])
    raise AttributeError(name)
